@HTS-371 @HTS-379
Feature: Applicant confirms details

  Scenario: Applicant confirms details
    Given an applicant has the following details:
      |field          |value            |
      |first name     |FirstName        |
      |last name      |LastName         |
      |NINO           |<auto-generated> |
      |date of birth  |20/12/1980       |
      |email address  |user@test.com    |

    When an applicant passes the eligibility check
    Then they see their details