language: scala
scala:
- 2.11.12
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
