language: scala
scala:
- 2.12.11
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
jdk:
- openjdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.4-precise
    packages:
    - mongodb-org-server
