@ignore
Feature: Applicant sees user details after passing eligibility check

  @qa
  Scenario: Applicant sees user details
    Given an applicant has the following details:
      |field          |value                |
      |name           |TestUser TestSurname |
      |NINO           |<auto-generated>     |
      |date of birth  |02/07/1941           |
      |email address  |user@test.com        |

    When an applicant passes the eligibility check
    Then they see their details
